<script lang='ts'>
    import { scale } from 'svelte/transition';

    let id = $state<string|null>(null);
    let name = $state('');
    let description = $state('');
    let { title, seriesData, show, closeModal, isEdit, save }:
        {title:string, seriesData: SeriesData|null, show: any, closeModal: any, isEdit: boolean, save: any } 
        = $props();

    $effect(() => {
        if (seriesData) {
            id = seriesData.id ?? null;
            name = seriesData.name ?? '';
            description = seriesData.description ?? '';
        }
    });

    async function createOrUpdateSeries() {
        if (!name) {
            alert("Name cannot be empty");
            return;
        }

        if (!description) {
            alert("Description cannot be empty");
            return;
        }

        if (isEdit)
        {
            if (!id)
            {
                alert(`Can't save series ${name} the id is missing are you sure this series has been created?`);
                return;
            }

            save({id, name, description})
        } else {
            save(name, description);
        }

        closeModal();
    }
</script>

{#if show}
    <div class="fixed inset-0 z-50 flex items-center justify-center">
        <button
            class="absolute inset-0 bg-black/60 backdrop-blur-sm"
            onclick={closeModal}
            aria-label="Close modal"
            type="button"
        ></button>

        <!-- panel -->
        <div class="relative bg-slate-900 border border-white/10 rounded-3xl w-full max-w-md p-8 shadow-2xl"
            transition:scale={{ duration: 200 }}>
            <div class="flex justify-between items-center mb-6">
                <h2 class="text-2xl font-bold text-white">{title}</h2>
                <button onclick={closeModal} class="text-slate-400 hover:text-white text-xl">✕</button>
            </div>

            <div class="space-y-4">
                {#if isEdit}
                <div>
                    <label class="text-slate-400 text-sm">ID
                        <input
                            bind:value={id}
                            disabled
                            class="w-full px-4 py-2 rounded-xl color-gray-600 border border-slate-700 text-white cursor-not-allowed bg-gray-600"
                        />
                    </label>
                    <p class="text-xs text-slate-500 mt-2">ID generated by the database and is therefore immutable.</p>
                </div>
                {/if}

                <div>
                    <label class="text-slate-400 text-sm">Name
                        <input
                            bind:value={name}
                            class="w-full px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-orange-500"
                        />
                    </label>
                </div>

                <div>
                    <label class="text-slate-400 text-sm">Description
                        <textarea
                            bind:value={description}
                            class="w-full px-4 py-2 rounded-xl bg-slate-800 border border-slate-700 text-white focus:outline-none focus:border-orange-500"
                        ></textarea>
                    </label>
                </div>

                <div class="flex justify-end gap-3 mt-4">
                    <button
                        onclick={closeModal}
                        class="px-4 py-2 bg-slate-700 hover:bg-slate-600 rounded-xl text-white"
                    >
                        Cancel
                    </button>
                    <button
                        onclick={createOrUpdateSeries}
                        class="px-4 py-2 bg-orange-600 hover:bg-orange-500 rounded-xl text-white"
                    >
                        {isEdit ? "Save" : "Add"}
                    </button>
                </div>
            </div>
        </div>
    </div>
{/if}